CREATE TABLE `elisad_delete`
(
    `ID`   INT          NOT NULL AUTO_INCREMENT,
    `DATE` DATETIME     NOT NULL,
    `TIP`  VARCHAR(250) NOT NULL,
    `PATH` VARCHAR(250) NOT NULL,
    PRIMARY KEY (`ID`)
);